### ISSUE TITLE
raspberry CM4 IO board design request

### ISSUE THREAD

**Issue by mgrouch** [Thomas-GeDaD/openplotter-MCS#6]
raspberry CM4 and IO boards look very promising

https://www.raspberrypi.org/products/compute-module-4-io-board/

There is a company which offers free design of the board on their web site
if you use their web site to spec it out.

Here is the link

https://www.gumstix.com/community/special-offer/

Their design studio

https://geppetto.gumstix.com/#!/dashboard/

Add number of NMEA interfaces, GPS, IMU, few 1-wire, One N2K
Safe Shutdown, 12v power in (+ AIS Chip possiblly)

to original CM4 IO Board and it could make a nice marine board 
replacing MCS and Moitessier Hat combo

using raspberry CM4.

Just an idea

Thanks,
--MG

**Comment by Thomas-GeDaD** [comment]
Hi mgrouch,
we worked on a cm adaptation of the MCS in a further Version. (But it takes a while, because i have also further projects... ) But GPS and Imo we make as an add on board to make the system flexible.  So not all want to use this and if all is on one board they mus t buy it if they want to use the other interfaces... Further we want to make all compatible to the actual mcs board...

**Comment by mgrouch** [comment]
They have promotion on gumstix website right now to wave design fees. Have you checked their website? geppetto tool looks nice. 


GPS is just cheap. 
Audio in/out 
12v in
Safe-shutdown 
RTC
4 NMEA 0183
1 CAN for n2k
Few 1wire ports
Ports to plugin amp/voltmeter 
antennas ports for WiFi/gps
AIS/LTE antenna (just ports to reroute from panel)
Some status lights 
Port for UPS battery or solar
Barometer temp/IMU (optional)
Relays to control nav/mast lights
Fridge controls

And other stuff which is already on IO board. 

Some ideas. 

Thanks!

**Comment by Thomas-GeDaD** [comment]
hi, Yes i have seen it. But not for interesting for us. When we develop electronic hardware, we use own software and experience. We must test the hardware later for CE and simular. And for this we do not use "any" online creator.
As described above, we worked on several further hardwar for Marine application. The most you described above is already intigrated in the availible hardware (see board specs and add ons) GPS and simular comes with add on boards for the MCS. This is "cheaper" and mor common for different user!
