### ISSUE TITLE
Seatalk1 with MCS server board

### ISSUE THREAD

**Issue by Tosca36** [Thomas-GeDaD/openplotter-MCS#7]
Seatalk1 transducers are analog, do you need to wire the transducers to the nmea0183 couplers as rs232 or rs422? Thank you

**Comment by Thomas-GeDaD** [comment]
Hi, this is an old not further supported Plugin:
https://github.com/Thomas-GeDaD/openplotter-MCS#attention

Use the SignalK Plugin. SignalK is the core of Openplotter so you can use it also on Openplotter!
Follow The Guide in the Manuals and the Plugin readme. There is all described. Also the handling of St1.
=>
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS#how-to-use-a-digital-input-in1-in4-for-seatalk1-reading
www.gedad.de/support
